config/routes.rb
Cookbook::Application.routes.draw do
  devise_for :users, :path => "", :path_names => {
    :sign_in => 'signin',
    :sign_out => 'signout',
    :sign_up => 'signup'
  }

  resources :recipes

  root :to => 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :title, :instructions
  
  belongs_to :created_by, class_name: User
  belongs_to :updated_by, class_name: User

  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :set_recipe
  before_filter :only_allow_creator, only: %w(edit update)

  # GET /recipes
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.created_by = @recipe.updated_by = current_user

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /recipes/1
  def update
    @recipe.updated_by = current_user

    if @recipe.update_attributes(params[:recipe])
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    redirect_to recipes_url
  end

  protected

    def set_recipe
      @recipe = Recipe.find(params[:id]) if params[:id]
    end

    def only_allow_creator
      redirect_to recipes_url, notice: 'You must be the creator of a recipe to edit it' unless @recipe.created_by_id === current_user.id
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def errors_for(model, attribute)
    content_tag :span, model.errors[attribute].first, class: 'help-block' unless model.errors[attribute].blank?
  end

  def error_class(model, attribute)
    'error' unless @recipe.errors[:title].blank?
  end

end

app/helpers/my_test_helper.rb
module MyTestHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Cookbook", root_path, class: "brand" %>
      <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li><p class="navbar-text">Signed in as <%= link_to current_user.email, edit_user_registration_path %></p></li>
          <li class="divider-vertical"></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: 'delete' %>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <% if notice %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= notice %>
    </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe, html: { class: 'form-horizontal' } do |f| %>

  <div class="control-group <%= error_class @recipe, :title %>">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'input-title span8' %>
      <%= errors_for @recipe, :title %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :instructions, class: 'control-label' %>
    <div class="controls"><%= f.text_area :instructions, class: 'span8' %></div>
  </div>

  <div class="form-actions">
    <%= f.submit "Save recipe", class: 'btn btn-primary' %>
    <%= link_to 'Cancel', :back, class: 'btn' %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<article>
  <header class="header">
    <h1>Edit recipe</h1>
  </header>

  <div class="content">
    <%= render 'form' %>
  </div>
</article>

app/views/recipes/index.html.erb
<article>
  <header class="header">
    <h1>Recipes</h1>
  </header>

  <div class="content">
    <table class="table table-hover table-flush-top">
      <tr>
        <th>Recipe</th>
        <th>Created by</th>
        <th>Last modified</th>
      </tr>

      <% @recipes.each do |recipe| %>
        <tr>
          <td>
            <strong><%= link_to recipe.title, recipe_path(recipe) %></strong>
            <% if recipe.created_by.try(:id) === current_user.id %>
              <%= link_to edit_recipe_path(recipe) do %><i class="icon-edit"></i><% end %>
              <%= link_to recipe_path(recipe), method: 'delete', confirm: "Are you sure?" do %><i class="icon-trash"></i><% end %>
            <% end %>
          </td>
          <td><%= recipe.created_by.try(:email) || 'unknown' %></td>
          <td><%= recipe.updated_at.to_date.to_s(:long) %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <%= link_to '<i class="icon-plus"></i>'.html_safe + " New recipe", new_recipe_path, class: 'btn btn-small' %>
</article>

app/views/recipes/new.html.erb
<article>
  <header class="header">
    <h1>New recipe</h1>
  </header>
  <div class="content">
    <%= render 'form' %>
  </div>
</article>

app/views/recipes/show.html.erb
<article>
  <header class="header">
    <h1><%= @recipe.title %></h1>
  </header>
  <div class="content">
    <%= simple_format @recipe.instructions %>
  </div>
</article>

<% if @recipe.created_by.try(:id) === current_user.id %>
  <%= link_to '<i class="icon-edit"></i>'.html_safe + ' Edit recipe', edit_recipe_path(@recipe), class: 'btn btn-small' %>
  <%= link_to '<i class="icon-trash"></i>'.html_safe + ' Delete', recipe_path(@recipe), method: 'delete', confirm: "Are you sure?", class: 'btn btn-small' %>
<% end %>